# Generated by Django 4.2.5 on 2023-10-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3rifeedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.IntegerField(max_length=10)),
                ('massage', models.CharField(max_length=300)),
            ],
        ),
    ]
